name: 3. Verificações de Segurança

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 0'  # Todo domingo à meia-noite

jobs:
  security:
    name: Análise de Segurança
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
          cache: true
      
      - name: Instalar dependências
        run: flutter pub get
      
      - name: Analisar vulnerabilidades com OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "flutter_poc_bm"
          path: "."
          format: "HTML"
          args: >
            --suppression ./.dependency-check-suppression.xml
            --failOnCVSS 7
            --enableExperimental
      
      - name: Publicar relatório de vulnerabilidades
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: reports
      
      - name: Verificar segredos expostos
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      
      - name: Notificar vulnerabilidades no Microsoft Teams
        if: failure()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.MS_TEAMS_WEBHOOK_URL }}
          title: "⚠️ Alerta de Segurança"
          summary: "Foram encontradas vulnerabilidades de segurança no build"
          text: |
            **Repositório:** ${{ github.repository }}
            **Branch:** ${{ github.ref }}
            **Commit:** ${{ github.sha }}
            
            Por favor, verifique o relatório de segurança para mais detalhes.
